apiVersion: apps/v1
kind: Deployment
metadata:
    name: boot-with-k8s
spec:
    replicas: 1
    selector:
    matchLabels:
        app: boot-with-k8s
    template:
    metadata:
        labels:
        app: boot-with-k8s
    spec:
        containers:
        - name: boot-with-k8s
        image: janardhan54/boot-with-k8s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090